### ISSUE TITLE
Use webpack for the build process and other improvements

### ISSUE THREAD

**Issue by LeoBorai** [jMuzsik/find-an-issue#6]
Hey! I just found your project and I find it useful! 

I would like to contribute to it! I was thinking that moving the source to webpack would be a good start in order to be able to use a bundler most of the community uses! 

I also have some ideas about your project I would like to share and I'm open to help making them happen!

If you are up to do it, let me know, and I will work on it and make a PR!

Thanks in advance!

**Comment by jmuzsik** [comment]
Hi, thanks for the interest @estebanborai! Though, the app already uses webpack! It's a `create-react-app` so it uses this script every time it builds: [file in create-react-app source code](https://github.com/facebook/create-react-app/blob/next/packages/react-scripts/scripts/build.js). The `create-react-app` team does things a little bit differently. Unless you meant something else?

Otherwise, I'm completely open to any ideas you may have!

**Comment by LeoBorai** [comment]
Well its okay! My idea in the first place was to add the capability to authenticate users.

With an authenticated user we are able to consume the GitHub API and with that the issues search. 

I was thinking about a custom issue search. 

Lets prettend the user most used language is JavaScript, when the user logs in we are able to filter and show selected data for the user, for example issues that involves using JavaScript, as the main language.

With the key to the API we are also able to creates lists for the user. Like top repositories, recommended issues and recent issues!

What do you think about it?

**Comment by jmuzsik** [comment]
I would be completely welcome to adding new features for the site. We can hold back on authentication for now but if you'd like to create pages specifically focused on languages like JavaScript or the like, by all means create the components and add the CSS, etc.

Though, to go into detail about your comments.

1. I am primarily content with how I handle using the API atm. I had to do thing's quite uniquely to get the data I wanted. I cannot think of a way that authentication can be very useful based upon the idea of the project. The main logic using the API is in the files in [this folder](https://github.com/jMuzsik/find-an-issue/tree/master/cron-job). Specifically the `handler.js` file. Check it out if curious.
2. The issue search is already quite custom, not beautiful but there are a lot of filters to get data, if you can think of other filters, by all means, let me know.
3. As said, if you want to make new views specifically for JS users or the like, create the view.
4. I don't understand the last thing you said. What to do with the API key that is. The project already is focused on top repos, to create recommended issues may be possible if there is an option for a user to say their experience level then specific labels can automatically be created for them. And recent issues, the issue search is already has that but it is true that it is not very attractive.

Mainly, i'd love more frontend features. Perhaps a view of the issue in its own page or dropdown. Or, a page specifically for JS users. Or a page based upon experience level. 

If you have any questions or any more ideas, please let me know. Thanks!

**Comment by LeoBorai** [comment]
Thanks for your fast answer!
The idea of the API Authentication is because GitHub asks you to authenticate to use the API (https://developer.github.com/v3/issues/). I wanted to create data filters when fetching the API in order to create lists to the user.

You can guess the user languages if the user is authenticated, you can read repos using the API, filter languages and make a pool, then filter issues for this user!

I think the *find-an-issue* project would be great if you can setup a custom experience for each user, this way the user is able to find issues of their interest and the site is up to date with GitHub!

So, that was my idea in the first intance! Hope you like it!
Thanks!

**Comment by jmuzsik** [comment]
I looked into the API for a while and the entire premise of this project is that you get repositories that are popular. The github API does not offer this. So, the only data that is useful from this project is what I already have stored in [this JSON file](https://github.com/jMuzsik/find-an-issue/blob/master/src/data.json). This data is updated two times a day. I do not use the GitHub API at all while the user uses the application.

So, because of this, unless you can think of useful ways to utilise the array from [this file](https://github.com/jMuzsik/find-an-issue/blob/master/cron-job/options.js) to get certain data from the API related to these popular projects I do not see a use case for using the API.

The only custom experience I can think of is... that when the user comes onto the site they are given data that already exists in that file that relates to some options that they checked while logged in, with possible notifications each time that the data is refreshed for issues that may interest them.  And, this is a sudden and not very calculated thought. There is a lot of directions that it can go. 

But still, I believe that the most useful thing would be more views. So that a user can click things and see a more in depth view.

Speaking of this, I have an idea of something worth implementing that would be useful if a user is logged in:

1. Every time the issue is clicked (add a button somewhere in the table for each issue). A new page is opened. When this button is clicked this API call occurs:  `https://api.github.com//repos/name_of_some_repo_owner/name_of_some_repo/issues/number_of_the_issue`
2. This will return some data corresponding with the issue. You'll get data like when you click this: [https://api.github.com/repos/nylas/nylas-mail/issues/3653](https://api.github.com/repos/nylas/nylas-mail/issues/3653)
3. Cherry pick this data and display what you think is meaningful. 

That'd be a nice feature.

Unless you have more ideas of what you'd rather do, then by all means let me know.

**Comment by LeoBorai** [comment]
Hey! Sorry I didnt reply before! I have been very busy the last days! I'm up to help anyway, I like your idea, I also though about turning the table into some kind of boxes? Like the repo boxes? In order to turn the design into a responsive design! Let me know if you are up to do it so I can take this approach and create a PR!

This is the "box" Im talking about:
![image](https://user-images.githubusercontent.com/34756077/45335947-d4192500-b557-11e8-9f7e-7678c3f18b4e.png)

Let me know your thoughts!

Thanks in advance!

Edit:
I will close this issue and if you are up for something create a PR and asign me!
I will be happy to help!

**Comment by jmuzsik** [comment]
Ok, I cannot assign you unless you're a collaborator. So I sent an email for that. Otherwise, I posted the issue! Thanks a lot!
